### ISSUE TITLE
The 1/3 million most frequent words from Google

### ISSUE THREAD

**Issue by dongyuwei** [siara-cc/Text_frequency_research#3]
https://norvig.com/ngrams/
The 1/3 million most frequent words, all lowercase, with counts

Hi, do you know this corpus data? It has good quality with accuracy word frequency.

**Comment by siara-cc** [comment]
Hi, thanks for sharing this and the question.
I have come across this corpus but I am seeing this 1/3 million frequent words only now.
It looks good, but I am mainly working on this project to make such a list of words/phrases so that I can use it in the [Unishox](https://github.com/siara-cc/Unishox) project (version 3). I would still have to build my own because of the following reasons:
- I need most frequent phrases as well, this one seems to have only list of frequent 2 words at best
- My source for compilation is reddit/twitter, which represents contemporary conversations, which IMO is more suited for compressing strings as the Unishox project best suits compression of chat exchanges.
- I need frequent words/phrases from different languages as well and not just Latin
- This would be a continuous exercise so if lists can be compiled from source this project would help
